openapi: 3.0.3

info:
  version: 1.0.0
  title: 👨🏼‍✈️ Gestión de Clientes 👩🏼‍✈️
  description: >
    API Rest para la gestión de clientes de un taller de mecánica
  contact:
    name: Grupo 10 
    url: 'https://moodle.upm.es/titulaciones/oficiales/mod/assign/view.php?id=95193'
    email: example.exampale@example.example

servers:
  - url: http://127.0.0.1:80/api/v1

tags:
  - name: 'Cliente'
    description: Cliente

paths:
  /cliente: 
    $ref: 'clientes.yaml'
  /clientes/{cliente_id}:
    $ref: 'clientes-by-id.yaml'

components:
  schemas:
    Cliente:
      $ref: 'schemas.yaml#/Cliente'
    Id_Cliente:
      $ref: 'schemas.yaml#/Id_Cliente'
    DNI_Cliente:
      $ref: 'schemas.yaml#/DNI_Cliente'
    Nombre_Cliente:
      $ref: 'schemas.yaml#/Nombre_Cliente'
    Apellidos_Cliente:
      $ref: 'schemas.yaml#/Apellidos_Cliente'
    Direccion_Cliente:
      $ref: 'schemas.yaml#/Direccion_Cliente'
    CuentaBancaria_Cliente:
      $ref: 'schemas.yaml#/CuentaBancaria_Cliente'
    Telefono: 
      $ref: 'schemas.yaml#/Telefono'
    Mail: 
      $ref: 'schemas.yaml#/Mail'
    HTTP_Problem:
      $ref: 'schemas.yaml#/HTTP_Problem'
    Link:
      $ref: 'schemas.yaml#/Link'
  
