apiVersion: v1
kind: Service 
metadata:
  name: trabajos
spec:
  selector: 
    app: trabajos
  ports:
    - port: 8030
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: trabajos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trabajos
  template:
    metadata:
      labels:
        app: trabajos
    spec:
      containers:
        - name: trabajos-fronted
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          env: 
            - name: SWAGGER_JSON
              value: /trabajos/openapi.yaml
          volumeMounts:
            - name: trabajos-frontend-volumen
              mountPath: /trabajos
              readOnly: true
      volumes:
        - name: trabajos-frontend-volumen
          persistentVolumeClaim:
            claimName: trabajos-frontend-volumen
            readOnly: true