apiVersion: v1
kind: Service
metadata:
  name: proxy
spec:
  selector:
    app: proxy
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: proxy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image: caddy:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: caddy-config
              mountPath: /etc/caddy/Caddyfile
            - name: caddy-data
              mountPath: /data
      volumes: 
        - name: caddy-config
          persistentVolumeClaim:
            claimName: caddy-config
        - name: caddy-data
          persistentVolumeClaim:
            claimName: caddy-data

